/**
 * @fileoverview Manual page for genesis init command
 */

import type { ManualPage } from "../core/types.ts";

export const initPage: ManualPage = {
  command: "genesis init",
  synopsis:
    "genesis init [site-name] [--template=basic|full|enterprise] [--port=N]",
  description: [
    "Initialize a new site within the Genesis hub-and-spoke project structure.",
    "",
    "Creates a complete site instance with symbolic links to the centralized",
    "core framework, enabling instant updates across all sites while maintaining",
    "site-specific configuration and assets. Each site operates independently",
    "on its own port but shares the core framework code via Unix symlinks.",
    "",
    "The command creates:",
    "  • Site directory structure (public/, config/, pages/)",
    "  • Symbolic links to core framework (utils, middleware, routes)",
    "  • Site-specific configuration file (site.config.ts)",
    "  • Default landing page and README documentation",
    "  • Port configuration (defaults to auto-assigned)",
    "",
    "Zero-configuration philosophy: Sensible defaults for everything,",
    "interactive prompts for essential details, no manual setup required.",
    "Run 'genesis dev' immediately after init to start developing.",
  ],
  philosophy: [
    '"Write programs that do one thing and do it well."',
    "",
    "The init command creates structure, nothing more.",
    "It doesn't install packages, compile code, or configure services.",
    "It creates directories and symbolic links. Pure. Simple. Unix.",
    "",
    "Each site is an independent instance sharing a common core.",
    "Update once, benefit everywhere. No version drift. No complexity.",
  ],
  sections: [
    {
      title: "ARCHITECTURE CREATED",
      content: [
        "project-root/",
        "├── core/              # Centralized framework (single source)",
        "├── sites/             # Individual site directories",
        "│   └── your-site/     # New site created by init command",
        "│       ├── public/    # Static assets (HTML, CSS, images)",
        "│       ├── utils →    # Symlink to ../../core/utils",
        "│       ├── middleware → ../../core/middleware",
        "│       ├── main.ts →  # Symlink to ../../core/main.ts",
        "│       └── site.config.ts  # Site-specific configuration",
        "├── shared/            # Shared resources across sites",
        "├── config/            # Global configuration",
        "├── logs/              # Centralized logging",
        "└── docs/              # Framework documentation",
      ],
    },
    {
      title: "INTERACTIVE PROMPTS",
      content: [
        "The init command guides you through setup with smart defaults:",
        "",
        "Site name:        Your site's identifier (required)",
        "Port number:      HTTP port (default: auto-assigned)",
        "Template type:    basic, full, or enterprise",
        "Description:      Optional site description",
        "",
        "All prompts include sensible defaults - just press Enter to accept.",
        "Use --skip-prompts flag with CLI arguments for non-interactive setup.",
      ],
    },
    {
      title: "OPTIONS",
      content: [
        "--template=basic       Minimal setup for simple projects",
        "--template=full        Complete setup with all features",
        "--template=enterprise  Enterprise features and monitoring",
        "",
        "--port=N               Specify custom port number",
        "--name=NAME            Set site name non-interactively",
        "--skip-prompts         Use defaults without prompting",
        "",
        "--verbose              Show detailed initialization steps",
        "--dry-run              Preview without creating files",
      ],
    },
    {
      title: "SYMBOLIC LINKING EXPLAINED",
      content: [
        "Sites use symbolic links (symlinks) to the core framework.",
        "This creates a 'single source of truth' architecture:",
        "",
        "sites/example/",
        "├── utils → ../../core/utils",
        "├── middleware → ../../core/middleware",
        "└── main.ts → ../../core/main.ts",
        "",
        "What this means:",
        "",
        "• Single Source: Core framework exists in one location only",
        "• Instant Updates: Changes to core immediately affect all sites",
        "• Zero Duplication: No copied code, no version drift",
        "• Reduced Disk Usage: Share code instead of duplicating it",
        "• Independent Sites: Each site has unique config and assets",
        "",
        "The symlink targets are:",
        "  utils, middleware, config, database, routes, controllers,",
        "  main.ts, VERSION, meta.ts, mod.ts",
      ],
    },
    {
      title: "AFTER INITIALIZATION",
      content: [
        "Once init completes, you'll see:",
        "",
        "✅ Genesis project initialized successfully!",
        "",
        "Site Details:",
        "  📁 Name: your-site",
        "  🌐 Port: 3000",
        "  📂 Path: sites/your-site",
        "  🔗 Core Links: 10 symlinks created",
        "",
        "Next Steps:",
        "  1. cd sites/your-site",
        "  2. genesis dev --port=3000",
        "  3. Open http://localhost:3000 in your browser",
        "",
        "Your site is ready to develop immediately - no build step,",
        "no package installation, no configuration required.",
      ],
    },
    {
      title: "EXAMPLES",
      content: [
        "# Basic usage with prompts",
        "genesis init",
        "",
        "# Specify site name directly",
        "genesis init my-awesome-site",
        "",
        "# Non-interactive with custom port",
        "genesis init my-site --port=3005 --skip-prompts",
        "",
        "# Enterprise template",
        "genesis init enterprise-app --template=enterprise",
        "",
        "# Preview without creating files",
        "genesis init test-site --dry-run --verbose",
      ],
    },
  ],
  seeAlso: ["new", "dev", "deploy"],
  version: "2.0.0",
};
